# Generated by Django 5.1.4 on 2025-01-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
