# Generated by Django 5.1.4 on 2025-01-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_album_slug_musicdirector_slug_playlist_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
